# name: CI

# on:
#   push:
#     branches:
#     - release/*

# jobs:
#   firebase-deploy:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@master
#     - uses: actions/setup-node@master
#       with:
#         node-version: '14.x'
#     - run: npm install
#     - run: npm run build:prod
#     - name: GitHub Action for Firebase
#       uses: w9jds/firebase-action@v2.0.0
#       with:
#         args: deploy --only hosting
#       env:
#         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
